######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 19 14:35:15 2011
######################################################################

MOC_DIR = ../tmp
OBJECTS_DIR = ../tmp
RCC_DIR = ../tmp
UI_DIR = ../tmp
DESTDIR = ../bin

TARGET = jsoncpp

TEMPLATE = lib
#CONFIG += debug
CONFIG += static

# Input
SOURCES += json_reader.cpp json_value.cpp json_writer.cpp
